steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "ENV=development",
        "-t",
        "gcr.io/coipond-dev/server",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/coipond-dev/server"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "server",
        "--image",
        "gcr.io/coipond-dev/server",
        "--region",
        "us-central1",
      ]
images:
  - gcr.io/coipond-dev/server
